services:
  backend:
    ports: !reset []
    environment:
      VIDEO_SOURCE: /dev/video0
    devices:
      - "/dev/video0:/dev/video0"
    network_mode: host
    networks: !reset null

  coturn:
    network_mode: host
    networks: !reset null

networks:
  app-network:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
        - subnet: "fd00:1:1::/64"
